import { atom } from "recoil";
import { IMentorInfo, ISlotInfo } from "./interface";

export const mentorToggleState = atom({
  key: "mentoToggle",
  default: false,
});

export const backgorundToggleState = atom({
  key: "backgroundToggle",
  default: false,
});

export const ScheduleToggleState = atom({
  key: "scheduleToggle",
  default: false,
});

export const ScheduleBackToggleState = atom({
  key: "schduleBackToggle",
  default: false,
});

export const StartIndexState = atom({
  key: "startIndex",
  default: -1,
});

export const EndIndexState = atom({
  key: "endIndex",
  default: -1,
});

export const MenteeNumberState = atom({
  key: "menteeNumber",
  default: 1,
});

export const SelectedSubjectState = atom({
  key: "selectedSubject",
  default: "",
});

export const SubjectDescriptionState = atom({
  key: "subjectDescription",
  default: "",
});

export const MentorInfoToggleState = atom({
  key: "mentorInfoToggle",
  default: false,
});

export const MentorInfoBackToggleState = atom({
  key: "mentorInfoBackToggle",
  default: false,
});

export const CurrentMentorInfoState = atom<IMentorInfo>({
  key: "currentMentorInfo",
  default: {
    intra: "inshin",
    level: 999,
    good: 10000,
    subjects: ["ft_transcendence"],
    image: "",
    coalition: "gon",
  },
});

export const CurrentSubjectInfoState = atom<{ subject: string; info: any }>({
  key: "currentSubjectInfoState",
  default: {
    subject: "",
    info: [],
  },
});

export const OpenedSlotsState = atom<ISlotInfo[]>({
  key: "openedSlots",
  default: [
    {
      mentor: "yooh",
      mentee: "",
      cur: 0,
      max: 3,
      subject: "inception",
      description: "docker의 시작과 끝",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 7.54,
      good: 452,
      coalition: "gun",
    },
    {
      mentor: "jbok",
      mentee: "",
      cur: 0,
      max: 3,
      subject: "inception",
      description: "docker의 시작과 끝",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 4.35,
      good: 252,
      coalition: "gun",
    },
    {
      mentor: "jbok",
      mentee: "",
      cur: 0,
      max: 3,
      subject: "philosopher bonus",
      description: "멀티..... 그잡채 ",
      start: 1681811100,
      end: 1681812900,
      image: "",
      level: 4.35,
      good: 252,
      coalition: "gun",
    },
    {
      mentor: "jbok",
      mentee: "",
      cur: 0,
      max: 3,
      subject: "libft",
      description: "복준석식 libft 들어간다 입벌려",
      start: 1681833600,
      end: 1681835400,
      image: "",
      level: 4.35,
      good: 252,
      coalition: "gun",
    },
    {
      mentor: "jbok",
      mentee: "",
      cur: 0,
      max: 3,
      subject: "libft",
      description: "libft = 죽음이다",
      start: 1681815600,
      end: 1681818300,
      image: "",
      level: 4.35,
      good: 252,
      coalition: "gun",
    },
    {
      mentor: "yooh",
      mentee: "jbok, jpark2",
      cur: 2,
      max: 3,
      subject: "inception",
      description: "CPP어려워요~",
      start: 1679101200,
      end: 1679103900,
      image: "",
      level: 7.54,
      good: 452,
      coalition: "gun",
    },
    {
      mentor: "inshin",
      mentee: "jbok, jpark2",
      cur: 2,
      max: 3,
      subject: "CPP BONUS",
      description: "CPP어려워요~",
      start: 1679101200,
      end: 1679103900,
      image: "",
      level: 10.54,
      good: 777,
      coalition: "gon",
    },
    {
      mentor: "yooh",
      mentee: "jbok",
      cur: 1,
      max: 1,
      subject: "minishell",
      description: "내 작고 소중한 미니쉘",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 7.54,
      good: 452,
      coalition: "gun",
    },
    {
      mentor: "jpark2",
      mentee: "jbok",
      cur: 1,
      max: 4,
      subject: "minishell bonus",
      description: "minishell.... a to z",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 6.54,
      good: 212,
      coalition: "gon",
    },
    {
      mentor: "sunwsong",
      mentee: "jdoh",
      cur: 1,
      max: 4,
      subject: "CPP 01 BONUS",
      description: "all about CPP",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gam",
    },
    {
      mentor: "jdoh",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "ft_transcendence",
      description: "Alpha and Omega",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gam",
    },
    {
      mentor: "jaesjeon",
      mentee: "",
      cur: 0,
      max: 4,
      subject: "ft_irc",
      description: "server andclient",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gun",
    },
    {
      mentor: "joopark",
      mentee: "",
      cur: 1,
      max: 2,
      subject: "webserv",
      description: "easy way to know http",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "hahseo",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "pipex",
      description: "mother of fd",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "lee",
    },
    {
      mentor: "jaham",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "ft_container bonus",
      description: "컨테이너 그 잡채",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gun",
    },
    {
      mentor: "mypark",
      mentee: "",
      cur: 0,
      max: 4,
      subject: "NetPractice",
      description: "Network gosu",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "heejkim",
      mentee: "jpark2",
      cur: 1,
      max: 1,
      subject: "cub3d",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "jaji",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "CPP 01 BONUS",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "jaji",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "CPP 00",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "jaji",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "CPP 02",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "jaji",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "CPP 03",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "jaji",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "CPP 04",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "jaji",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "CPP 05",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "jaji",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "CPP 06",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "jaji",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "CPP 07",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "jaji",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "CPP 08",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "jaji",
      mentee: "",
      cur: 0,
      max: 1,
      subject: "CPP 09",
      description: "ray tracing",
      start: 1679106600,
      end: 1679107500,
      image: "",
      level: 4.01,
      good: 62,
      coalition: "gon",
    },
    {
      mentor: "yeckim",
      mentee: "",
      cur: 3,
      max: 3,
      subject: "minishell",
      description:
        "minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell minishell ",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 10.0,
      good: 252,
      coalition: "lee",
    },

    {
      mentor: "hoslim",
      mentee: "",
      cur: 4,
      max: 3,
      subject: "CPP 05",
      description: "C PLUS PLUS의 정점",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 9.28,
      good: 252,
      coalition: "gun",
    },

    {
      mentor: "hojsong",
      mentee: "",
      cur: 6,
      max: 3,
      subject: "ft_container",
      description: "사라진 container의 역사를 알아보는 시간을 가져 봅시다",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 4.35,
      good: 252,
      coalition: "gon",
    },

    {
      mentor: "wonljeon",
      mentee: "",
      cur: 2,
      max: 3,
      subject: "push_swap",
      description: "최고의 비효율을 자랑하는 두개의 스택으로 정렬하는법",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 4.35,
      good: 252,
      coalition: "gam",
    },
    {
      mentor: "seongmpa",
      mentee: "",
      cur: 1,
      max: 3,
      subject: "libft",
      description: "어서와 태초마을은 처음이지? libft와 함께라면 두렵지 않아요",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 12,
      good: 252,
      coalition: "lee",
    },
    {
      mentor: "chajung",
      mentee: "",
      cur: 1,
      max: 3,
      subject: "ft_printf",
      description: "\\ ;",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 9.28,
      good: 252,
      coalition: "gun",
    },
    {
      mentor: "chajung",
      mentee: "",
      cur: 1,
      max: 3,
      subject: "Born2beroot",
      description: "\\ ;",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 9.28,
      good: 252,
      coalition: "gun",
    },
    {
      mentor: "joonhan",
      mentee: "",
      cur: 1,
      max: 3,
      subject: "get_next_line",
      description: "\\ ;",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 9.28,
      good: 252,
      coalition: "gun",
    },
    {
      mentor: "joonhan",
      mentee: "",
      cur: 1,
      max: 3,
      subject: "Fdf",
      description: "\\ ;",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 9.28,
      good: 252,
      coalition: "gun",
    },
    {
      mentor: "joonhan",
      mentee: "",
      cur: 1,
      max: 3,
      subject: "so_long",
      description: "\\ ;",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 9.28,
      good: 252,
      coalition: "gun",
    },
    {
      mentor: "joonhan",
      mentee: "",
      cur: 1,
      max: 3,
      subject: "so_long",
      description: "\\ ;",
      start: 1679014800,
      end: 1679015700,
      image: "",
      level: 9.28,
      good: 252,
      coalition: "gun",
    },
  ],
});
