# Generated by Django 4.1.7 on 2023-03-15 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User42',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, unique=True)),
                ('image', models.CharField(default=None, max_length=256, null=True)),
                ('level', models.FloatField(default=0.0)),
                ('mentor_cnt', models.IntegerField(default=0)),
                ('feedback1', models.IntegerField(default=0)),
                ('feedback2', models.IntegerField(default=0)),
                ('feedback3', models.IntegerField(default=0)),
                ('feedback4', models.IntegerField(default=0)),
                ('feedback5', models.IntegerField(default=0)),
                ('total_time', models.DurationField(default=datetime.timedelta(0))),
                ('token', models.BinaryField(default=b'')),
            ],
        ),
    ]
