# Generated by Django 4.1.7 on 2023-03-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user42',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
