# Generated by Django 4.1.7 on 2023-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0002_alter_user42_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user42',
            name='login',
            field=models.CharField(max_length=20),
        ),
    ]
