# Generated by Django 4.1.7 on 2023-03-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0008_openslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openslot',
            name='intra_id',
        ),
        migrations.AddField(
            model_name='openslot',
            name='login',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
