# Generated by Django 4.1.7 on 2023-03-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0009_remove_openslot_intra_id_openslot_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user42',
            name='coa',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
