# Generated by Django 4.1.7 on 2023-03-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0013_alter_openslot_login_alter_openslot_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openslot',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='login',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='subject_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
