# Generated by Django 4.1.7 on 2023-03-16 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0014_alter_openslot_description_alter_openslot_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openslot',
            name='duration',
        ),
        migrations.AddField(
            model_name='openslot',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='description',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
