# Generated by Django 4.1.7 on 2023-03-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0016_alter_openslot_end_time_alter_openslot_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openslot',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
