# Generated by Django 4.1.7 on 2023-03-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0017_alter_openslot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user42',
            name='login',
            field=models.CharField(max_length=16),
        ),
    ]
