# Generated by Django 4.1.7 on 2023-03-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0019_openslot_mentee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openslot',
            name='mentee',
        ),
        migrations.AddField(
            model_name='openslot',
            name='mentee1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='openslot',
            name='mentee2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='openslot',
            name='mentee3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='openslot',
            name='mentee4',
            field=models.IntegerField(default=-1),
        ),
    ]
