# Generated by Django 4.1.7 on 2023-03-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0020_remove_openslot_mentee_openslot_mentee1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openslot',
            name='coa',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='openslot',
            name='level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mento', to='pm42.user42'),
        ),
        migrations.AlterField(
            model_name='user42',
            name='login',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
