# Generated by Django 4.1.7 on 2023-03-16 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0021_openslot_coa_openslot_level_alter_openslot_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openslot',
            old_name='login',
            new_name='mento',
        ),
    ]
