# Generated by Django 4.1.7 on 2023-03-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0024_alter_openslot_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openslot',
            name='left',
            field=models.IntegerField(default=4),
        ),
    ]
