# Generated by Django 4.1.7 on 2023-03-16 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0025_alter_openslot_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openslot',
            name='mentee1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentee1', to='pm42.user42'),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='mentee2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentee2', to='pm42.user42'),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='mentee3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentee3', to='pm42.user42'),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='mentee4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentee4', to='pm42.user42'),
        ),
    ]
