# Generated by Django 4.1.7 on 2023-03-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0026_alter_openslot_mentee1_alter_openslot_mentee2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openslot',
            name='subject_name',
            field=models.CharField(max_length=256),
        ),
    ]
