# Generated by Django 4.1.7 on 2023-03-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0027_alter_openslot_subject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openslot',
            old_name='final_mark',
            new_name='bonus',
        ),
        migrations.RemoveField(
            model_name='openslot',
            name='coa',
        ),
        migrations.RemoveField(
            model_name='openslot',
            name='level',
        ),
        migrations.AddField(
            model_name='openslot',
            name='login',
            field=models.CharField(default='yooh', max_length=16),
            preserve_default=False,
        ),
    ]
