# Generated by Django 4.1.7 on 2023-03-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0028_rename_final_mark_openslot_bonus_remove_openslot_coa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openslot',
            old_name='subject_name',
            new_name='subject',
        ),
    ]
