# Generated by Django 4.1.7 on 2023-03-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0029_rename_subject_name_openslot_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openslot',
            name='mentee1',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='mentee2',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='mentee3',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='mentee4',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
