# Generated by Django 4.1.7 on 2023-03-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0031_alter_openslot_mentee1_alter_openslot_mentee2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openslot',
            name='left',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='max',
            field=models.IntegerField(default=1),
        ),
    ]
