# Generated by Django 4.1.7 on 2023-03-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0032_alter_openslot_left_alter_openslot_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openslot',
            name='mento',
        ),
    ]
