# Generated by Django 4.1.7 on 2023-03-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0033_remove_openslot_mento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openslot',
            old_name='login',
            new_name='mento',
        ),
    ]
