# Generated by Django 4.1.7 on 2023-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0034_rename_login_openslot_mento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user42',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
