# Generated by Django 4.1.7 on 2023-03-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0038_alter_user42_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user42',
            name='token',
        ),
    ]
