# Generated by Django 4.1.7 on 2023-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0039_remove_user42_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user42',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
