# Generated by Django 4.1.7 on 2023-03-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0040_user42_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='openslot',
            name='finished',
            field=models.IntegerField(default=0),
        ),
    ]
