# Generated by Django 4.1.7 on 2023-03-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0042_remove_openslot_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openslot',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='openslot',
            old_name='start_time',
            new_name='start',
        ),
    ]
