# Generated by Django 4.1.7 on 2023-03-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0044_rename_mento_openslot_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user42',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
