# Generated by Django 4.1.7 on 2023-03-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm42', '0046_remove_openslot_mentee1_remove_openslot_mentee2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user42',
            name='feedback1',
        ),
        migrations.RemoveField(
            model_name='user42',
            name='feedback2',
        ),
        migrations.RemoveField(
            model_name='user42',
            name='feedback3',
        ),
        migrations.RemoveField(
            model_name='user42',
            name='feedback4',
        ),
        migrations.RemoveField(
            model_name='user42',
            name='feedback5',
        ),
    ]
